### ISSUE TITLE
Will this be continued?

### ISSUE THREAD

**Issue by DasLixou** [rust-tutorials/learn-opengl#9]

**Comment by Lokathor** [comment]
Unlikely. The repo is based on the C version of the tutorial, and what's written so far is, I think, enough that a person can look at the rest of the C tutorials and continue if they'd like. Particularly, a lot of the code in later tutorials is mostly changes to the GLSL, so those are even easier to do.

I could accept PRs with more examples translated, but otherwise I expect people will largely be moving to `wgpu` in the coming years, so I'd expect people to want to read that guide instead https://sotrh.github.io/learn-wgpu/

**Comment by DasLixou** [comment]
Thats pretty sad. But ok
